import { Movie } from './types';

export const SEED_MOVIES: Movie[] = [
  {
    id: 335984,
    title: "Blade Runner 2049",
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    poster_path: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/ilRyAZwxiPTgRLLoqOfLR2daFFE.jpg",
    release_date: "2017-10-04",
    vote_average: 8.0,
    genres: ["Science Fiction", "Mystery", "Drama"],
    runtime: 164,
    tagline: "The key to the future is finally unearthed.",
    trailer_key: "g4Hbz2jLxvQ",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    streaming_providers: [{ name: "Max", type: "stream" }, { name: "Prime Video", type: "rent" }]
  },
  {
    id: 157336,
    title: "Interstellar",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    poster_path: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.4,
    genres: ["Adventure", "Drama", "Science Fiction"],
    runtime: 169,
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    trailer_key: "zSWdZVtXT7E",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    streaming_providers: [{ name: "Paramount+", type: "stream" }, { name: "Prime Video", type: "rent" }]
  },
  {
    id: 496243,
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    genres: ["Comedy", "Thriller", "Drama"],
    runtime: 132,
    tagline: "Act like you own the place.",
    trailer_key: "isOGD_7hNIY",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 693134,
    title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    release_date: "2024-02-27",
    vote_average: 8.2,
    genres: ["Science Fiction", "Adventure"],
    runtime: 166,
    tagline: "Long live the fighters.",
    trailer_key: "Way9Dexny3w",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    streaming_providers: [{ name: "Max", type: "stream" }, { name: "Prime Video", type: "rent" }]
  },
  {
    id: 872585,
    title: "Oppenheimer",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    release_date: "2023-07-19",
    vote_average: 8.1,
    genres: ["Drama", "History"],
    runtime: 180,
    tagline: "The world forever changes.",
    trailer_key: "uYPbbksJxIg",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    streaming_providers: [{ name: "Peacock", type: "stream" }, { name: "Prime Video", type: "rent" }]
  },
  {
    id: 244786,
    title: "Whiplash",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, pushing his mind and body to their limits.",
    poster_path: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/vNXGrknWJOHtqWbV3X0kPeblMcl.jpg",
    release_date: "2014-10-10",
    vote_average: 8.4,
    genres: ["Drama", "Music"],
    runtime: 107,
    tagline: "The road to greatness can take you to the edge.",
    trailer_key: "7d_jQycdQGo",
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser"],
    streaming_providers: [{ name: "Netflix", type: "stream" }]
  },
  {
    id: 546554,
    title: "Knives Out",
    overview: "When renowned crime novelist Harlan Thrombey is found dead at his estate, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.",
    poster_path: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    release_date: "2019-11-27",
    vote_average: 7.9,
    genres: ["Comedy", "Mystery", "Crime"],
    runtime: 130,
    tagline: "Hell, any of them could have done it.",
    trailer_key: "xi-1NchUqMA",
    director: "Rian Johnson",
    cast: ["Daniel Craig", "Ana de Armas", "Chris Evans", "Jamie Lee Curtis"],
    streaming_providers: [{ name: "Prime Video", type: "stream" }]
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    overview: "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider-Society.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    release_date: "2023-05-31",
    vote_average: 8.4,
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    runtime: 140,
    tagline: "It's how you wear the mask that matters.",
    trailer_key: "cqGjhVJWtEg",
    director: "Joaquim Dos Santos, Kemp Powers",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    streaming_providers: [{ name: "Netflix", type: "stream" }]
  },
  {
    id: 27205,
    title: "Inception",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered impossible: inception.",
    poster_path: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    release_date: "2010-07-15",
    vote_average: 8.4,
    genres: ["Action", "Science Fiction", "Adventure"],
    runtime: 148,
    tagline: "Your mind is the scene of the crime.",
    trailer_key: "YoHD9XEInc0",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 155,
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    poster_path: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    release_date: "2008-07-16",
    vote_average: 8.5,
    genres: ["Drama", "Action", "Crime", "Thriller"],
    runtime: 152,
    tagline: "Why so serious?",
    trailer_key: "EXeTwQWrcwY",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 120467,
    title: "The Grand Budapest Hotel",
    overview: "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
    poster_path: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/5nyz5bCmsm2z9h3Kk2PqGvF9R8D.jpg",
    release_date: "2014-02-26",
    vote_average: 8.0,
    genres: ["Comedy", "Drama"],
    runtime: 100,
    tagline: "A murder case of aristocratic proportions.",
    trailer_key: "1Fg5iWmQjwk",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan", "Willem Dafoe"],
    streaming_providers: [{ name: "Hulu", type: "stream" }]
  },
  {
    id: 329865,
    title: "Arrival",
    overview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    poster_path: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/y2A5tF0Tf7tE7gO3z9f6yMv9n9j.jpg",
    release_date: "2016-11-10",
    vote_average: 7.6,
    genres: ["Drama", "Science Fiction", "Mystery"],
    runtime: 116,
    tagline: "Why are they here?",
    trailer_key: "tFMo3UJ4B4g",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    streaming_providers: [{ name: "Paramount+", type: "stream" }]
  },
  {
    id: 76600,
    title: "Avatar: The Way of Water",
    overview: "Set more than a decade after the events of the first film, learn the story of the Sully family, the trouble that follows them, the lengths they go to keep each other safe, and the battles they fight to stay alive.",
    poster_path: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    release_date: "2022-12-14",
    vote_average: 7.7,
    genres: ["Science Fiction", "Adventure", "Action"],
    runtime: 192,
    tagline: "Return to Pandora.",
    trailer_key: "d9MyW72ELq0",
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    streaming_providers: [{ name: "Disney+", type: "stream" }]
  },
  {
    id: 313369,
    title: "La La Land",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars.",
    poster_path: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/qJeU799ZrnYn2l9l6x6w9Wn5kQ2.jpg",
    release_date: "2016-11-29",
    vote_average: 7.9,
    genres: ["Comedy", "Drama", "Romance", "Music"],
    runtime: 128,
    tagline: "Here's to the fools who dream.",
    trailer_key: "0pdqf4P9MB8",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    streaming_providers: [{ name: "Netflix", type: "stream" }]
  },
  {
    id: 550,
    title: "Fight Club",
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town.",
    poster_path: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    release_date: "1999-10-15",
    vote_average: 8.4,
    genres: ["Drama"],
    runtime: 139,
    tagline: "Mischief. Mayhem. Soap.",
    trailer_key: "dfeUzm6KF4g",
    director: "David Fincher",
    cast: ["Edward Norton", "Brad Pitt", "Helena Bonham Carter"],
    streaming_providers: [{ name: "Hulu", type: "stream" }]
  },
  {
    id: 680,
    title: "Pulp Fiction",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    poster_path: "https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    release_date: "1994-09-10",
    vote_average: 8.5,
    genres: ["Thriller", "Crime"],
    runtime: 154,
    tagline: "Just because you are a character doesn't mean you have character.",
    trailer_key: "s7EdQ4FqbhY",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 429617,
    title: "Spider-Man: Far From Home",
    overview: "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures causing natural catastrophes.",
    poster_path: "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/t7D3u0JtG4i0Bf8k3G0bQ1fN7k2.jpg",
    release_date: "2019-06-28",
    vote_average: 7.5,
    genres: ["Action", "Adventure", "Science Fiction"],
    runtime: 129,
    tagline: "It's time to step up.",
    trailer_key: "Nt9L1jCKGnE",
    director: "Jon Watts",
    cast: ["Tom Holland", "Samuel L. Jackson", "Jake Gyllenhaal", "Zendaya"],
    streaming_providers: [{ name: "Disney+", type: "stream" }]
  },
  {
    id: 419430,
    title: "Get Out",
    overview: "Chris and his girlfriend Rose have reached the meet-the-parents milestone of dating, she invites him for a weekend getaway upstate. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
    poster_path: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/m5zbh88vC9r5yG9p1Ff7G5K8q7.jpg",
    release_date: "2017-02-24",
    vote_average: 7.6,
    genres: ["Mystery", "Thriller", "Horror"],
    runtime: 104,
    tagline: "Just because you're invited, doesn't mean you're welcome.",
    trailer_key: "DzfpyUB60YY",
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    streaming_providers: [{ name: "Peacock", type: "stream" }]
  },
  {
    id: 597,
    title: "Titanic",
    overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship.",
    poster_path: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg",
    release_date: "1997-11-18",
    vote_average: 7.9,
    genres: ["Drama", "Romance"],
    runtime: 194,
    tagline: "Nothing on Earth could come between them.",
    trailer_key: "2e-eXJ6HgkQ",
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
    streaming_providers: [{ name: "Paramount+", type: "stream" }]
  },
  {
    id: 11,
    title: "Star Wars: A New Hope",
    overview: "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to restore freedom and justice to the Galaxy.",
    poster_path: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgPn7q9nUHQxtAN0eg.jpg",
    release_date: "1977-05-25",
    vote_average: 8.2,
    genres: ["Adventure", "Action", "Science Fiction"],
    runtime: 121,
    tagline: "A long time ago in a galaxy far, far away...",
    trailer_key: "vZ734NWnAHA",
    director: "George Lucas",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
    streaming_providers: [{ name: "Disney+", type: "stream" }]
  },
  {
    id: 603,
    title: "The Matrix",
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    poster_path: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/7u3fh95kn3mUVp10K2Z2uUq6H4D.jpg",
    release_date: "1999-03-30",
    vote_average: 8.2,
    genres: ["Action", "Science Fiction"],
    runtime: 136,
    tagline: "Welcome to the Real World.",
    trailer_key: "vKQi3bBA1y8",
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 1578,
    title: "Raging Bull",
    overview: "The life of boxer Jake LaMotta, who's violence and temper that lead him to the top in the ring destroys his life outside of it.",
    poster_path: "https://image.tmdb.org/t/p/w500/1WV7WlTS8LI1L5NkCgjWT9GSW3O.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/vG9QnF2P8mGzWq1N8lG6g5zX8M.jpg",
    release_date: "1980-11-14",
    vote_average: 8.0,
    genres: ["Drama"],
    runtime: 129,
    tagline: "His behavior outside the ring was worse than his brutal behavior in it.",
    trailer_key: "yUp6d79WRVI",
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Cathy Moriarty", "Joe Pesci"],
    streaming_providers: [{ name: "Prime Video", type: "stream" }]
  },
  {
    id: 238,
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.",
    poster_path: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWF9YFaoZq09u7K6i.jpg",
    release_date: "1972-03-14",
    vote_average: 8.7,
    genres: ["Drama", "Crime"],
    runtime: 175,
    tagline: "An offer you can't refuse.",
    trailer_key: "sY1S34973zA",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    streaming_providers: [{ name: "Paramount+", type: "stream" }]
  },
  {
    id: 77,
    title: "Memento",
    overview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.",
    poster_path: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/tXQvlqBvK2bYp0GqWkXwHwVzS9k.jpg",
    release_date: "2000-10-11",
    vote_average: 8.2,
    genres: ["Mystery", "Thriller"],
    runtime: 113,
    tagline: "Some memories are best forgotten.",
    trailer_key: "4CV41hoyS8A",
    director: "Christopher Nolan",
    cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
    streaming_providers: [{ name: "Prime Video", type: "stream" }]
  },
  {
    id: 118340,
    title: "Guardians of the Galaxy",
    overview: "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering a mysterious orb wanted by Ronan the Accuser.",
    poster_path: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/uLtVingCrMy4Yx09Ur8whj7hQZ9.jpg",
    release_date: "2014-07-30",
    vote_average: 7.9,
    genres: ["Action", "Science Fiction", "Adventure"],
    runtime: 121,
    tagline: "All heroes start somewhere.",
    trailer_key: "d96cjJhvlMA",
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Bradley Cooper"],
    streaming_providers: [{ name: "Disney+", type: "stream" }]
  },
  {
    id: 49026,
    title: "The Dark Knight Rises",
    overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane.",
    poster_path: "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/c3rL39Vn9h9A8v7K5V1hQyB1uB2.jpg",
    release_date: "2012-07-16",
    vote_average: 7.8,
    genres: ["Action", "Crime", "Drama", "Thriller"],
    runtime: 165,
    tagline: "The Legend Ends.",
    trailer_key: "g8evyE9TuYk",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
    streaming_providers: [{ name: "Max", type: "stream" }]
  },
  {
    id: 9362,
    title: "Tremors",
    overview: "Hick handymen Val and Earl can't wait to leave the desert town of Perfection, Nevada until dead bodies turn up and they discover gigantic prehistoric carnivorous worms hunting beneath the soil.",
    poster_path: "https://image.tmdb.org/t/p/w500/cA4ggkZ3r1d5r9hOAUWC8x5ul2i.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/8tU8sDkW2d4Z6O9D5s5Z5jG5F5f.jpg",
    release_date: "1990-01-19",
    vote_average: 7.0,
    genres: ["Comedy", "Horror", "Science Fiction"],
    runtime: 96,
    tagline: "They say there's nothing new under the sun. But under the ground...",
    trailer_key: "7RrT44WRr-4",
    director: "Ron Underwood",
    cast: ["Kevin Bacon", "Fred Ward", "Finn Carter", "Michael Gross"],
    streaming_providers: [{ name: "Prime Video", type: "stream" }]
  },
  {
    id: 25373,
    title: "A Cry in the Wild",
    overview: "Based on the acclaimed novel 'Hatchet' by Gary Paulsen. 13-year-old Brian is the sole survivor of a deadly plane crash in the rugged Canadian wilderness. Armed with only a survival hatchet, he must battle the brutal elements and wildlife to stay alive.",
    poster_path: "https://image.tmdb.org/t/p/w500/o2xNHWOk6jXmwm1Cqbv1HAjByWf.jpg",
    release_date: "1990-06-01",
    vote_average: 6.8,
    genres: ["Adventure", "Drama"],
    runtime: 82,
    tagline: "Alone. Afraid. Armed with only a hatchet.",
    trailer_key: "e5Lx2V6gNZQ",
    director: "Mark Griffiths",
    cast: ["Jared Rushton", "Pamela Sue Martin", "Ned Beatty"],
    streaming_providers: [{ name: "Prime Video", type: "stream" }]
  },
  {
    id: 37165,
    title: "The Truman Show",
    overview: "Truman Burbank is the star of 'The Truman Show', a 24-hour-a-day reality TV program that broadcasts every aspect of his life without his knowledge.",
    poster_path: "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    release_date: "1998-06-04",
    vote_average: 8.1,
    genres: ["Comedy", "Drama", "Science Fiction"],
    runtime: 103,
    tagline: "On the air. Unaware.",
    trailer_key: "dlnmQbPGuls",
    director: "Peter Weir",
    cast: ["Jim Carrey", "Laura Linney", "Ed Harris"],
    streaming_providers: [{ name: "Paramount+", type: "stream" }]
  }
];
